- file:
    path: /cider-ci/data/config
    state: directory

###############################################################################

# - file:
#     path: /cider-ci/data/config/vars.yml
#     state: absent
#

- stat:
    path: /cider-ci/data/config/vars.yml
  register: vars_file_stat

- template:
    src: vars.yml
    dest: /cider-ci/data/config/vars.yml
  when: not vars_file_stat.stat.exists

###############################################################################

- stat:
    path: /cider-ci/data/config/config.yml
  register: config_file_stat

- template:
    src: config.yml
    dest: /cider-ci/data/config/config.yml
  when: not config_file_stat.stat.exists

