- file:
    path: /cider-ci/data/config
    state: directory

###############################################################################

- update_secrets:
    path: /cider-ci/data/config/secrets.yml
    keys:
      - database_secret
      - management_secret
      - messaging_secret
      - services_basic_auth_secret
      - session_secret

###############################################################################

- stat:
    path: /cider-ci/data/config/config.yml
  register: config_file_stat

- template:
    src: config.yml
    dest: /cider-ci/data/config/config.yml
  when: not config_file_stat.stat.exists

