- file:
    path: /cider-ci/data/config
    state: directory

- file:
    path: /cider-ci/data/config/vars.yml
    state: absent

- stat:
    path: /cider-ci/data/config/vars.yml
  register: vars_file_stat

#- shell: cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
#  args:
  #    executable: /usr/bin/bash
  #register: rand_str

- shell: dd if=/dev/urandom bs=256 count=1 | tr -dc 'a-zA-Z0-9'
  register: rand_str

#- shell: apg -d
#  register: rand_str

- template:
    src: vars.yml
    dest: /cider-ci/data/config/vars.yml
  when: not vars_file_stat.stat.exists


