name: cider-ci_v4/server-container
windows:
  '2':
    name: docker2
    command: |
      eval $(docker-machine env vmware)
  '3':
    name: docker3
    command: |
      eval $(docker-machine env vmware)
