- template:
    src: rabbitmq-env.conf
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: 0644

- service:
    name: rabbitmq-server
    enabled: yes
    state: started

- rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- rabbitmq_user:
    name: cider-ci
    node: rabbit@localhost
    state: absent

- rabbitmq_vhost:
    name: cider-ci
    node: rabbit@localhost
    state: absent

- rabbitmq_vhost:
    name: cider-ci
    node: rabbit@localhost
    state: present

- rabbitmq_user:
    node: rabbit@localhost
    user: cider-ci
    force: yes
    password: "{{messaging_secret}}"
    vhost: cider-ci
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: management
