
### General ###################################################################

job_retention_duration: 50 Years

db_backups_enabled: False

user_interface_statement_timeout_milliseconds: 3000


### Secrets ###################################################################

database_secret: secret

messaging_secret: secret

secret_key_base: {{lookup('pipe', "dd if=/dev/urandom bs=256 count=1 | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1")}}

services_basic_auth_secret: {{lookup('pipe', "dd if=/dev/urandom bs=256 count=1 | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1")}}

