job_retention_duration: "{{job_retention_duration}}"

database:
  adapter: postgresql
  classname: org.postgresl.Driver
  subname: '//localhost:5432/cider-ci'
  subprotocol: postgresql
  user: cider-ci
  password: "{{database_secret}}"
  max_pool_size: 3

github_authtoken: {{github_authtoken | default('NULL',true) }}

hostname: localhost

secret: "{{secret_key_base}}"

basic_auth:
  username: service
  password: "{{services_basic_auth_secret}}"

session:
  secret: "{{secret_key_base}}"

messaging:
  connection:
    vhost: cider-ci
    host: localhost
    username: cider-ci
    password: "{{messaging_secret}}"


server_base_url: "http://localhost"

services:

  api:

    http:
      host: localhost
      port: 8885
      context: /cider-ci
      sub_context: /api
      ssl: false

    nrepl:
      port: 7885
      bind: localhost
      enabled: true

    database:
      max_pool_size: 10

  builder:

    http:
      host: localhost
      port: 8884
      context: /cider-ci
      sub_context: /builder
      ssl: false

    nrepl:
      port: 7884
      bind: localhost
      enabled: true

    database:
      max_pool_size: 10


  dispatcher:

    http:
      host: localhost
      port: 8882
      context: '/cider-ci'
      sub_context: '/dispatcher'
      ssl: false

    nrepl:
      port: 7882
      bind: localhost
      enabled: true

    database:
      max_pool_size: 30

    dispatch_interval: 0.25



  notifier:

    http:
      host: localhost
      port: 8887
      context: /cider-ci
      sub_context: /notifier
      ssl: false

    nrepl:
      port: 7887
      bind: localhost
      enabled: true

    database:
      max_pool_size: 10


  repository:

    http:
      host: localhost
      port: 8881
      context: /cider-ci
      sub_context: /repositories
      ssl: false

    nrepl:
      port: 7881
      bind: localhost
      enabled: true

    database:
      max_pool_size: 20

    repositories:
      path: /cider-ci/data/repositories


  storage:

    http:
      host: localhost
      port: 8886
      context: /cider-ci
      sub_context: /storage
      ssl: false

    nrepl:
      port: 7886
      bind: localhost
      enabled: true

    database:
      max_pool_size: 10

    stores:

      - url_path_prefix: /trial-attachments
        file_path: /cider-ci/data/attachments/trial-attachments
        db_table: trial_attachments

      - url_path_prefix: /tree-attachments
        file_path: /cider-ci/data/attachments/tree-attachments
        db_table: tree_attachments

  ui:

    http:
      host: localhost
      port: 8880
      context: /cider-ci
      sub_context: /ui
      ssl: false

